// frontend/src/components/Sparkline.tsx
interface Props {
  values: number[];
  width?: number;
  height?: number;
  positive: boolean;
}

export function Sparkline({ values, width = 100, height = 28, positive }: Props) {
  if (values.length < 2) return <svg width={width} height={height} />;

  const lo = Math.min(...values);
  const hi = Math.max(...values);
  const span = hi - lo || 1;
  const step = width / (values.length - 1);

  const points = values
    .map((v, i) => `${(i * step).toFixed(1)},${(height - ((v - lo) / span) * height).toFixed(1)}`)
    .join(' ');

  return (
    <svg width={width} height={height} className="sparkline">
      <polyline points={points} fill="none" stroke={positive ? 'var(--good)' : 'var(--bad)'} strokeWidth={1.5} />
    </svg>
  );
}

// frontend/src/components/Sparkline.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = withDefaults(
  defineProps<{ values: number[]; width?: number; height?: number; positive: boolean }>(),
  { width: 100, height: 28 },
);

const points = computed(() => {
  if (props.values.length < 2) return '';
  const lo = Math.min(...props.values);
  const hi = Math.max(...props.values);
  const span = hi - lo || 1;
  const step = props.width / (props.values.length - 1);
  return props.values
    .map((v, i) => `${(i * step).toFixed(1)},${(props.height - ((v - lo) / span) * props.height).toFixed(1)}`)
    .join(' ');
});
</script>

<template>
  <svg v-if="values.length < 2" :width="width" :height="height" />
  <svg v-else :width="width" :height="height" class="sparkline">
    <polyline :points="points" fill="none" :stroke="positive ? 'var(--good)' : 'var(--bad)'" stroke-width="1.5" />
  </svg>
</template>
