// frontend/src/components/Spinner.vue
<script setup lang="ts">
withDefaults(defineProps<{ size?: number }>(), { size: 14 });
</script>

<template>
  <svg :width="size" :height="size" viewBox="0 0 24 24" class="spinner" fill="none">
    <circle cx="12" cy="12" r="9" stroke="currentColor" stroke-opacity="0.25" stroke-width="3" />
    <path d="M21 12a9 9 0 0 0-9-9" stroke="currentColor" stroke-width="3" stroke-linecap="round" />
  </svg>
</template>

// frontend/src/components/Spinner.tsx
interface Props {
  size?: number;
}

export function Spinner({ size = 14 }: Props) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" className="spinner" fill="none">
      <circle cx="12" cy="12" r="9" stroke="currentColor" strokeOpacity="0.25" strokeWidth="3" />
      <path d="M21 12a9 9 0 0 0-9-9" stroke="currentColor" strokeWidth="3" strokeLinecap="round" />
    </svg>
  );
}
