// frontend/src/components/SubmitButton.tsx
import type { ReactNode } from 'react';
import { Spinner } from './Spinner';

interface Props {
  busy: boolean;
  busyLabel?: string;
  children: ReactNode;
}

export function SubmitButton({ busy, busyLabel = 'Running…', children }: Props) {
  return (
    <button type="submit" disabled={busy} className="submit-btn">
      {busy ? (
        <>
          <Spinner size={14} /> {busyLabel}
        </>
      ) : (
        children
      )}
    </button>
  );
}

// frontend/src/components/SubmitButton.vue
<script setup lang="ts">
import Spinner from './Spinner.vue';

withDefaults(defineProps<{ busy: boolean; busyLabel?: string }>(), { busyLabel: 'Running…' });
</script>

<template>
  <button type="submit" :disabled="busy" class="submit-btn">
    <template v-if="busy">
      <Spinner :size="14" /> {{ busyLabel }}
    </template>
    <slot v-else />
  </button>
</template>
