// frontend/src/components/charts/FanChart.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Line } from 'vue-chartjs';
import type { ChartData, ChartOptions, TooltipItem } from 'chart.js';
import { cssVar, hexToRgba } from '../../utils/cssVar';
import { useThemeVersion } from '../../composables/useThemeVersion';
import type { BandPoint } from '../../types';

const props = withDefaults(defineProps<{ data: BandPoint[]; yLabel?: string }>(), { yLabel: 'Value' });

const themeVersion = useThemeVersion();

function fmt(v: number): string {
  return v.toLocaleString(undefined, { maximumFractionDigits: 2 });
}

// dataset order: [p5, p95(fills to p5), p25, p75(fills to p25), median]
const TOOLTIP_RANK = [4, 0, 3, 1, 2]; // rank per datasetIndex: p95,p75,median,p25,p5

const chartData = computed<ChartData<'line'>>(() => {
  void themeVersion.value;
  const seriesColor = cssVar('--series-1');
  const border = cssVar('--border');
  return {
    labels: props.data.map((d) => String(d.step)),
    datasets: [
      { label: 'p5', data: props.data.map((d) => d.p5), borderWidth: 0, pointRadius: 0, fill: false, borderColor: border },
      { label: 'p95', data: props.data.map((d) => d.p95), borderWidth: 0, pointRadius: 0, backgroundColor: hexToRgba(seriesColor, 0.12), fill: 0 },
      { label: 'p25', data: props.data.map((d) => d.p25), borderWidth: 0, pointRadius: 0, fill: false, borderColor: border },
      { label: 'p75', data: props.data.map((d) => d.p75), borderWidth: 0, pointRadius: 0, backgroundColor: hexToRgba(seriesColor, 0.28), fill: 2 },
      { label: 'median', data: props.data.map((d) => d.p50), borderColor: seriesColor, borderWidth: 2, pointRadius: 0, fill: false },
    ],
  };
});

const chartOptions = computed<ChartOptions<'line'>>(() => {
  void themeVersion.value;
  const muted = cssVar('--muted');
  const border = cssVar('--border');
  const panelRaised = cssVar('--panel-raised');
  const text = cssVar('--text');
  return {
    responsive: true,
    maintainAspectRatio: false,
    animation: false,
    interaction: { mode: 'index', intersect: false },
    plugins: {
      legend: { display: false },
      tooltip: {
        backgroundColor: panelRaised,
        titleColor: muted,
        bodyColor: text,
        borderColor: border,
        borderWidth: 1,
        itemSort: (a: TooltipItem<'line'>, b: TooltipItem<'line'>) =>
          TOOLTIP_RANK[a.datasetIndex] - TOOLTIP_RANK[b.datasetIndex],
        callbacks: {
          title: (items: TooltipItem<'line'>[]) => `Day ${items[0]?.label ?? ''}`,
          label: (item: TooltipItem<'line'>) => `${item.dataset.label}: ${fmt(item.parsed.y ?? 0)}`,
        },
      },
    },
    scales: {
      x: {
        grid: { display: false },
        ticks: { color: muted, font: { size: 11 } },
        title: { display: true, text: 'Trading day', color: muted, font: { size: 11 } },
      },
      y: {
        grid: { color: border },
        ticks: { color: muted, font: { size: 11 } },
        title: { display: true, text: props.yLabel, color: muted, font: { size: 11 } },
      },
    },
  };
});
</script>

<template>
  <div class="chart-card">
    <div class="chart-legend">
      <span><i class="legend-swatch" style="background: var(--series-1); opacity: 0.15" /> 5th-95th percentile</span>
      <span><i class="legend-swatch" style="background: var(--series-1); opacity: 0.3" /> 25th-75th percentile</span>
      <span><i class="legend-swatch line" style="background: var(--series-1)" /> median</span>
    </div>
    <div style="height: 280px">
      <Line :data="chartData" :options="chartOptions" />
    </div>
  </div>
</template>

// frontend/src/components/charts/FanChart.tsx
import {
  Area, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis,
} from 'recharts';
import type { BandPoint } from '../../types';

interface TooltipProps {
  active?: boolean;
  payload?: { payload: BandPoint }[];
  label?: number;
}

function fmt(v: number): string {
  return v.toLocaleString(undefined, { maximumFractionDigits: 2 });
}

function FanTooltip({ active, payload, label }: TooltipProps) {
  if (!active || !payload || !payload.length) return null;
  const point = payload[0].payload;
  return (
    <div className="chart-tooltip">
      <div className="chart-tooltip-label">Day {label}</div>
      <div className="chart-tooltip-row"><span>p95</span><strong>{fmt(point.p95)}</strong></div>
      <div className="chart-tooltip-row"><span>p75</span><strong>{fmt(point.p75)}</strong></div>
      <div className="chart-tooltip-row"><span>median</span><strong>{fmt(point.p50)}</strong></div>
      <div className="chart-tooltip-row"><span>p25</span><strong>{fmt(point.p25)}</strong></div>
      <div className="chart-tooltip-row"><span>p5</span><strong>{fmt(point.p5)}</strong></div>
    </div>
  );
}

export function FanChart({ data, yLabel = 'Value' }: { data: BandPoint[]; yLabel?: string }) {
  const chartData = data.map((d) => ({ ...d, band90: [d.p5, d.p95], band50: [d.p25, d.p75] }));

  return (
    <div className="chart-card">
      <div className="chart-legend">
        <span><i className="legend-swatch" style={{ background: 'var(--series-1)', opacity: 0.15 }} /> 5th-95th percentile</span>
        <span><i className="legend-swatch" style={{ background: 'var(--series-1)', opacity: 0.3 }} /> 25th-75th percentile</span>
        <span><i className="legend-swatch line" style={{ background: 'var(--series-1)' }} /> median</span>
      </div>
      <ResponsiveContainer width="100%" height={280}>
        <ComposedChart data={chartData} margin={{ top: 8, right: 12, left: 0, bottom: 8 }}>
          <CartesianGrid stroke="var(--border)" vertical={false} />
          <XAxis
            dataKey="step" stroke="var(--muted)" tick={{ fill: 'var(--muted)', fontSize: 11 }}
            label={{ value: 'Trading day', position: 'insideBottom', offset: -4, fill: 'var(--muted)', fontSize: 11 }}
          />
          <YAxis
            stroke="var(--muted)" tick={{ fill: 'var(--muted)', fontSize: 11 }} width={64}
            label={{ value: yLabel, angle: -90, position: 'insideLeft', fill: 'var(--muted)', fontSize: 11 }}
          />
          <Tooltip content={<FanTooltip />} />
          <Area dataKey="band90" stroke="none" fill="var(--series-1)" fillOpacity={0.12} isAnimationActive={false} />
          <Area dataKey="band50" stroke="none" fill="var(--series-1)" fillOpacity={0.28} isAnimationActive={false} />
          <Line dataKey="p50" stroke="var(--series-1)" strokeWidth={2} dot={false} isAnimationActive={false} />
        </ComposedChart>
      </ResponsiveContainer>
    </div>
  );
}
