// frontend/src/components/charts/TrendLineChart.tsx
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

export interface FundamentalsTrendRow {
  fiscal_year: number;
  revenue?: number | null;
  net_income?: number | null;
  free_cash_flow?: number | null;
}

const SERIES = [
  { key: 'revenue', label: 'Revenue', color: 'var(--series-1)' },
  { key: 'net_income', label: 'Net income', color: 'var(--series-2)' },
  { key: 'free_cash_flow', label: 'Free cash flow', color: 'var(--series-3)' },
] as const;

function fmt(v: number): string {
  const abs = Math.abs(v);
  if (abs >= 1e9) return `$${(v / 1e9).toFixed(1)}B`;
  if (abs >= 1e6) return `$${(v / 1e6).toFixed(1)}M`;
  return `$${v.toFixed(0)}`;
}

interface TooltipEntry {
  dataKey: string;
  value: number;
}

function TrendTooltip({ active, payload, label }: { active?: boolean; payload?: TooltipEntry[]; label?: number }) {
  if (!active || !payload || !payload.length) return null;
  return (
    <div className="chart-tooltip">
      <div className="chart-tooltip-label">FY{label}</div>
      {SERIES.map((s) => {
        const entry = payload.find((p) => p.dataKey === s.key);
        if (!entry || entry.value == null) return null;
        return (
          <div className="chart-tooltip-row" key={s.key}>
            <span><i className="legend-swatch line" style={{ background: s.color }} /> {s.label}</span>
            <strong>{fmt(entry.value)}</strong>
          </div>
        );
      })}
    </div>
  );
}

export function TrendLineChart({ data }: { data: FundamentalsTrendRow[] }) {
  return (
    <div className="chart-card">
      <ResponsiveContainer width="100%" height={260}>
        <LineChart data={data} margin={{ top: 8, right: 12, left: 8, bottom: 8 }}>
          <CartesianGrid stroke="var(--border)" vertical={false} />
          <XAxis dataKey="fiscal_year" stroke="var(--muted)" tick={{ fill: 'var(--muted)', fontSize: 11 }} />
          <YAxis stroke="var(--muted)" tick={{ fill: 'var(--muted)', fontSize: 11 }} tickFormatter={fmt} width={56} />
          <Tooltip content={<TrendTooltip />} />
          <Legend wrapperStyle={{ fontSize: 12, color: 'var(--muted)' }} />
          {SERIES.map((s) => (
            <Line
              key={s.key} dataKey={s.key} name={s.label} stroke={s.color} strokeWidth={2} dot={false}
              connectNulls isAnimationActive={false}
            />
          ))}
        </LineChart>
      </ResponsiveContainer>
    </div>
  );
}

// frontend/src/components/charts/TrendLineChart.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Line } from 'vue-chartjs';
import type { ChartData, ChartOptions, TooltipItem } from 'chart.js';
import { cssVar } from '../../utils/cssVar';
import { useThemeVersion } from '../../composables/useThemeVersion';

export interface FundamentalsTrendRow {
  fiscal_year: number;
  revenue?: number | null;
  net_income?: number | null;
  free_cash_flow?: number | null;
}

const SERIES = [
  { key: 'revenue', label: 'Revenue', color: '--series-1' },
  { key: 'net_income', label: 'Net income', color: '--series-2' },
  { key: 'free_cash_flow', label: 'Free cash flow', color: '--series-3' },
] as const;

const props = defineProps<{ data: FundamentalsTrendRow[] }>();

const themeVersion = useThemeVersion();

function fmt(v: number): string {
  const abs = Math.abs(v);
  if (abs >= 1e9) return `$${(v / 1e9).toFixed(1)}B`;
  if (abs >= 1e6) return `$${(v / 1e6).toFixed(1)}M`;
  return `$${v.toFixed(0)}`;
}

const chartData = computed<ChartData<'line'>>(() => {
  void themeVersion.value;
  return {
    labels: props.data.map((d) => String(d.fiscal_year)),
    datasets: SERIES.map((s) => ({
      label: s.label,
      data: props.data.map((d) => d[s.key] ?? null),
      borderColor: cssVar(s.color),
      borderWidth: 2,
      pointRadius: 0,
      spanGaps: true,
      fill: false,
    })),
  };
});

const chartOptions = computed<ChartOptions<'line'>>(() => {
  void themeVersion.value;
  const muted = cssVar('--muted');
  const border = cssVar('--border');
  const panelRaised = cssVar('--panel-raised');
  const text = cssVar('--text');
  return {
    responsive: true,
    maintainAspectRatio: false,
    animation: false,
    interaction: { mode: 'index', intersect: false },
    plugins: {
      legend: { display: true, labels: { color: muted, font: { size: 12 } } },
      tooltip: {
        backgroundColor: panelRaised,
        titleColor: muted,
        bodyColor: text,
        borderColor: border,
        borderWidth: 1,
        callbacks: {
          title: (items: TooltipItem<'line'>[]) => `FY${items[0]?.label ?? ''}`,
          label: (item: TooltipItem<'line'>) => `${item.dataset.label}: ${fmt(item.parsed.y ?? 0)}`,
        },
      },
    },
    scales: {
      x: {
        grid: { display: false },
        ticks: { color: muted, font: { size: 11 } },
      },
      y: {
        grid: { color: border },
        ticks: { color: muted, font: { size: 11 }, callback: (v) => fmt(Number(v)) },
      },
    },
  };
});
</script>

<template>
  <div class="chart-card">
    <div style="height: 260px">
      <Line :data="chartData" :options="chartOptions" />
    </div>
  </div>
</template>
