// frontend/src/pages/PredictPage.vue
<script setup lang="ts">
import { ref } from 'vue';
import { api, ApiError } from '../api';
import ErrorBox from '../components/ErrorBox.vue';
import SubmitButton from '../components/SubmitButton.vue';
import type { useModels } from '../composables/useModels';
import type { PredictResponse } from '../types';

type ModelOptions = ReturnType<typeof useModels>;
defineProps<{ modelOptions: ModelOptions }>();

const modelId = ref('');
const busy = ref(false);
const result = ref<PredictResponse | null>(null);
const error = ref<Error | null>(null);

async function onSubmit() {
  if (!modelId.value) {
    error.value = new Error('choose a trained model first');
    return;
  }
  busy.value = true;
  error.value = null;
  result.value = null;
  try {
    result.value = await api.predict({ model_id: Number(modelId.value) });
  } catch (err) {
    error.value = err instanceof ApiError ? err : new Error(String(err));
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <section>
    <h2>Predict next-period direction</h2>
    <form class="run-form" @submit.prevent="onSubmit">
      <fieldset :disabled="busy" class="run-form-fields">
        <label>
          Model
          <select v-model="modelId">
            <option value="">(load models first)</option>
            <option v-for="m in modelOptions.models" :key="m.id" :value="String(m.id)">
              #{{ m.id }} {{ m.ticker }} {{ m.model_type }} (test acc {{ m.test_accuracy.toFixed(2) }})
            </option>
          </select>
        </label>
        <SubmitButton :busy="busy" busy-label="Predicting…">Predict</SubmitButton>
      </fieldset>
    </form>
    <div class="result">
      <ErrorBox v-if="error" :error="error" />
      <p v-if="result">
        {{ result.ticker }}:
        <span :class="`direction ${result.direction === 'UP' ? 'up' : 'down'}`">{{ result.direction }}</span>
        next {{ result.horizon }}-day move &mdash; P(up)={{ result.prob_up.toFixed(3) }}
      </p>
    </div>
  </section>
</template>

// frontend/src/pages/PredictPage.tsx
import { useState } from 'react';
import { api, ApiError } from '../api';
import { ErrorBox } from '../components/ErrorBox';
import { SubmitButton } from '../components/SubmitButton';
import type { useModels } from '../hooks/useModels';
import type { PredictResponse } from '../types';

type ModelOptions = ReturnType<typeof useModels>;

export function PredictPage({ modelOptions }: { modelOptions: ModelOptions }) {
  const [modelId, setModelId] = useState('');
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<PredictResponse | null>(null);
  const [error, setError] = useState<Error | null>(null);

  async function onSubmit(evt: React.FormEvent) {
    evt.preventDefault();
    if (!modelId) {
      setError(new Error('choose a trained model first'));
      return;
    }
    setBusy(true);
    setError(null);
    setResult(null);
    try {
      const response = await api.predict({ model_id: Number(modelId) });
      setResult(response);
    } catch (err) {
      setError(err instanceof ApiError ? err : new Error(String(err)));
    } finally {
      setBusy(false);
    }
  }

  return (
    <section>
      <h2>Predict next-period direction</h2>
      <form className="run-form" onSubmit={onSubmit}>
        <fieldset disabled={busy} className="run-form-fields">
          <label>
            Model
            <select value={modelId} onChange={(e) => setModelId(e.target.value)}>
              <option value="">(load models first)</option>
              {modelOptions.models.map((m) => (
                <option key={m.id} value={m.id}>
                  #{m.id} {m.ticker} {m.model_type} (test acc {m.test_accuracy.toFixed(2)})
                </option>
              ))}
            </select>
          </label>
          <SubmitButton busy={busy} busyLabel="Predicting…">Predict</SubmitButton>
        </fieldset>
      </form>
      <div className="result">
        {error && <ErrorBox error={error} />}
        {result && (
          <p>
            {result.ticker}:{' '}
            <span className={`direction ${result.direction === 'UP' ? 'up' : 'down'}`}>{result.direction}</span>{' '}
            next {result.horizon}-day move &mdash; P(up)={result.prob_up.toFixed(3)}
          </p>
        )}
      </div>
    </section>
  );
}
